name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies 
      run: | 
        sudo apt-get update 
        sudo apt-get install -y docker.io make
      
    - name: Start Docker 
      run: sudo systemctl start docker 
      
    - name: Build PHP for Android 
      run: make 
    
    - name: Upload built libraries 
      uses: actions/upload-artifact@v4 
      with: 
        name: php-android-libs 
        path: app/src/main/jniLibs
